### ISSUE TITLE
Could not get a front to work

### ISSUE THREAD

**Issue by vdeturckheim** [strues/boldr#201]
Hello, I was trying this project. I had an issue with the front: I got this as a webapge with an error in the console:
`Uncaught ReferenceError: vendor is not defined`

![error](https://cloud.githubusercontent.com/assets/7135896/19930132/4c0bd448-a107-11e6-8efb-3880cc601988.png)

Browser: Chrome
Nodejs: 6.9 and then 7

**Comment by strues** [comment]
If you start and stop the development command once or twice the problem resolves itself. Im looking into the issue. I believe it to be a problem somewhere with Webpack's DLL implementation and HappyPack.

**Comment by vdeturckheim** [comment]
Thanks, I will take a look again :)

**Comment by vdeturckheim** [comment]
I still have a hard time here after a few tentative.
Can you ping me when it will be solved? 

Thanks a lot :)

**Comment by strues** [comment]
@vdeturckheim From what I can tell, Ive solved the issue this morning.

https://github.com/boldr/boldr/commit/bb7987bf80df8e915f8896a0077da4c9e003c9a8

Please let me know if it works (or doesnt)
