### ISSUE TITLE
Look and feel

### ISSUE THREAD

**Issue by strues** [strues/boldr#30]
The style, component structure, and user experience needs to come together. Most of this has been ignored in favor of prioritizing getting functionality.

**Comment by davidgustys** [comment]
Hey @strues just wanted to write here, and let you know that its a very nice project you are developing here, especially I like the clean, thought out, clear structure of the code that you have here -  very easy to follow. And yeah re postgres vs rethink, i think posgres makes more sense as its more widely used + has nice json functionality.., re graphql i think it is a nice idea, but for the moment I myself am sticking to regular REST endpoints..., so yeah keep up the good job..

P.S you can delete this comment afterwards..

**Comment by strues** [comment]
Thanks @gdeividas I appreciate it!
