### ISSUE TITLE
Forgot Password Feature

### ISSUE THREAD

**Issue by cloudcompute** [strues/boldr#48]
I am thrilled by the speed you're working on this project. 

I request you to add the Forgot Password feature in the Login Form and the verification email is sent at the user's email address is sent.

Thanks in anticipation

**Comment by strues** [comment]
9dcbd7f includes the backend for working password modifications (reset, change, and forgot)

**Comment by cloudcompute** [comment]
Thanks, Strues.

I hope that the user will be able to reset his password in the User Profile window.

**Comment by cloudcompute** [comment]
I consider this as one of the best open source React-Redux projects 
https://github.com/sars/appetini-front

It has a lot of functionality implemented like Recovery Form, Pagination. I think you can copy it from there and integrate with your backend.
